### ISSUE TITLE
Slower process

### ISSUE THREAD

**Issue by edan81** [Pkcs11Interop/pkcs11-logger#10]
HI Jariq

Thank you so much for apps you share, but I have one question. Why does PKCS admin if Load library using pkcs logger is faster then not using it ? ex : new Pkcs11Library(pkcs11Library, pkcs11Logger); it take 90ms and if I only use new Pkcs11Library(pkcs11Library); it's takes time 4000ms. please advise

**Comment by jariq** [comment]
No idea.
