### ISSUE TITLE
Using direct logger dll, without pkcs11admin logger facility

### ISSUE THREAD

**Issue by fliot** [Pkcs11Interop/pkcs11-logger#19]
Hi,

Just for clearing potential doubts,
1) Using directly my legacy pkcs11 dll, works perfectly
2) Using legacy pkcs11 dll with pkcs11admin logging facility work perfectly

But, trying to use directly the pkcs11-logger dll, it fails.
By design ? An error ? Quite strange, isn't it ? Please explain.

![image (1)](https://github.com/user-attachments/assets/29b7416e-1288-46cb-ab51-85a062878cbd)

**Comment by jariq** [comment]
No idea 🤷🏻

**Comment by fliot** [comment]
Ok, thanks for answering.
