### ISSUE TITLE
looks like a break is missing in translate.c

### ISSUE THREAD

**Issue by viperomega** [Pkcs11Interop/pkcs11-logger#4]
Hi,

for me a added "break;" fix this build problem and imho fix a possible wrong return value.

./build.sh                       
rm -f *.o
rm -f *.so
gcc -m32 -Wall -Wextra -Werror -O2 -I../../src -fPIC -c ../../src/init.c
gcc -m32 -Wall -Wextra -Werror -O2 -I../../src -fPIC -c ../../src/lock.c
gcc -m32 -Wall -Wextra -Werror -O2 -I../../src -fPIC -c ../../src/log.c
gcc -m32 -Wall -Wextra -Werror -O2 -I../../src -fPIC -c ../../src/pkcs11-logger.c
gcc -m32 -Wall -Wextra -Werror -O2 -I../../src -fPIC -c ../../src/translate.c
../../src/translate.c: In function ‘pkcs11_logger_translate_ck_rv’:
../../src/translate.c:295:21: error: this statement may fall through [-Werror=implicit-fallthrough=]
             rv_name = "CKR_VENDOR_DEFINED";
             ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
../../src/translate.c:296:9: note: here
         default:
         ^~~~~~~
cc1: all warnings being treated as errors
Makefile.x86:32: recipe for target 'translate.o' failed
make: *** [translate.o] Error 1

**Comment by jariq** [comment]
Of course `break` should be there. I'll fix it in the next release. Thanks for reporting.
