### ISSUE TITLE
Environment variable PKCS11_LOGGER_LIBRARY_PATH is not defined

### ISSUE THREAD

**Issue by Frank667** [Pkcs11Interop/pkcs11-logger#9]
I know there was a similar ticket from a windows user, but I see no solution for the problem that I could use.

__Used OS__: CentOS 8

I have added the exports for PKCS11_LOGGER_LIBRARY_PATH and the rest to the .bashrc and when I 
run "env | grep PKCS11" the output is as follows:
PKCS11_LOGGER_LOG_FILE_PATH=/home/ejbca/pkcs11_debug.log
PKCS11_LOGGER_LIBRARY_PATH=/usr/lib64/pkcs11/yubihsm_pkcs11.so
PKCS11_LOGGER_FLAGS=16

I have double checked that the yubihsm-library does exist. Is there something obvious I didn't see?

Regard,
Frank

**Comment by jariq** [comment]
Hello Frank, environment variables seem to be set correctly. What are your next steps? Are you executing some application that loads `pkcs11-logger-x64.so`?

**Comment by Frank667** [comment]
Yes, I try to run the test from the ejbca clienttoolbox:
sudo ./ejbcaClientToolBox.sh PKCS11HSMKeyTool test /usr/lib64­/pkcs11/pkcs11-logger-x64.so 0

But I think I found it out myself. I exported the variables from .bashrc of my user and did the "env | grep PKCS11" the same way. The problem seems to be the "sudo" in front of the command. I moved the export of the variables to /etc/profile.d/pkcs11.sh and this seems to do the trick. 
Sorry for bothering you with such a stupid mistake. Perhaps you could clarify the documentation a little so other will not make the same mistake?

Cheers,
Frank
